In [1]:
from google.colab import files
uploaded = files.upload()

Saving movies.csv to movies.csv


In [2]:
# importing dependencies
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Pre Processing

In [3]:
# loading the data from the csv file to pandas dataframe
movies_data = pd.read_csv('movies.csv')

In [4]:
# first five rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [5]:
# no.of rows and columns 
movies_data.shape

(4803, 24)

In [81]:
# selecting the relevant features for recommendation
selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [82]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [83]:
# replacing the null values with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [84]:
# containing all the 5 selected features

combined_features = movies_data['genres'] + movies_data['keywords'] + movies_data['tagline'] + movies_data['cast'] + movies_data['director'] + movies_data['overview']

In [85]:
print(combined_features)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [86]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [87]:
feature_vector = vectorizer.fit_transform(combined_features)

In [88]:
print(feature_vector)

  (0, 7211)	0.15785649032038593
  (0, 1428)	0.11989857008807574
  (0, 1729)	0.05218744162287104
  (0, 31503)	0.16246949894069793
  (0, 1767)	0.03029299085900534
  (0, 29053)	0.15399515630559496
  (0, 15616)	0.1375264729723761
  (0, 4070)	0.09485675276006127
  (0, 40265)	0.14002976378399234
  (0, 3685)	0.09296257980287868
  (0, 5664)	0.05874061446709645
  (0, 26678)	0.10488796921224784
  (0, 41643)	0.14686488493102665
  (0, 28923)	0.0470169768892924
  (0, 26966)	0.1460008156074791
  (0, 40135)	0.02943613143327801
  (0, 11221)	0.1757655714895802
  (0, 21025)	0.039545466180595595
  (0, 25249)	0.13812800605810213
  (0, 29605)	0.19223425482279902
  (0, 6545)	0.12047111075071086
  (0, 256)	0.18693252297203264
  (0, 5877)	0.19906937596983335
  (0, 33610)	0.2087029381560179
  (0, 26349)	0.1182593486000071
  :	:
  (4802, 40777)	0.08561045088611684
  (4802, 39396)	0.06943049448630909
  (4802, 28551)	0.06678960321620862
  (4802, 17909)	0.08507855285433547
  (4802, 43146)	0.08406102416253504
  (48

Cosine Similarity

In [89]:
# getiing similarity score using cosine similarity

similarity = cosine_similarity(feature_vector)

In [90]:
print(similarity)

[[1.         0.04633911 0.02108447 ... 0.02546564 0.03220701 0.0067216 ]
 [0.04633911 1.         0.03935666 ... 0.04621248 0.03190481 0.01639624]
 [0.02108447 0.03935666 1.         ... 0.0256327  0.0119989  0.01472549]
 ...
 [0.02546564 0.04621248 0.0256327  ... 1.         0.03888249 0.02053173]
 [0.03220701 0.03190481 0.0119989  ... 0.03888249 1.         0.03414082]
 [0.0067216  0.01639624 0.01472549 ... 0.02053173 0.03414082 1.        ]]


In [91]:
print(similarity.shape)

(4803, 4803)


In [92]:
# getting the movie name from the user

movie_name = input("Enter your favourite movie name : ")

Enter your favourite movie name : iron man


In [93]:
# creating a list with all the movie given in the dataset

list_of_all_titles = movies_data['title'].tolist()

In [94]:
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [95]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

In [96]:
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [97]:
close_match = find_close_match[0]
print(close_match)


Iron Man


In [98]:
from pandas._libs import index
# finding the index of the movie with the title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

print(index_of_the_movie)

68


In [99]:
# Getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))

print(similarity_score)

[(0, 0.035244616280315375), (1, 0.02278707345592209), (2, 0.006553095103989156), (3, 0.00656713743725125), (4, 0.017082111703362414), (5, 0.010435410456572439), (6, 0.01628515128794128), (7, 0.13057945394765283), (8, 0.005722306329675693), (9, 0.017910075262681336), (10, 0.012272308489376323), (11, 0.005600997989783219), (12, 0.0019354484477916514), (13, 0.0075926633986009625), (14, 0.029393356714719973), (15, 0.014168552300580409), (16, 0.11039721469015037), (17, 0.008735730436893144), (18, 0.013917349866119826), (19, 0.008799872075460975), (20, 0.03350242219796348), (21, 0.022384429125405617), (22, 0.0052593105900779966), (23, 0.00512188260570401), (24, 0.008992817969872755), (25, 0.00356478150023445), (26, 0.08816216485654467), (27, 0.0175358457384564), (28, 0.032685336842021975), (29, 0.006204747979726135), (30, 0.057944413684934214), (31, 0.2291184057608786), (32, 0.01951039825030638), (33, 0.07367517021639296), (34, 0.0055267036458631616), (35, 0.018932482535930308), (36, 0.02384

In [100]:
len(similarity_score)

4803

In [101]:
# sorting movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse=True)

print(sorted_similar_movies)

[(68, 1.0000000000000002), (31, 0.2291184057608786), (79, 0.20457341529402867), (7, 0.13057945394765283), (4401, 0.1243152569559969), (16, 0.11039721469015037), (26, 0.08816216485654467), (64, 0.07634816238897932), (1406, 0.07506834892126425), (46, 0.07396772219514824), (33, 0.07367517021639296), (1282, 0.07128923528432592), (2235, 0.07101956718819993), (4325, 0.06804458701389997), (2063, 0.06747748776560993), (394, 0.06741020178188568), (725, 0.06703204584380618), (421, 0.06682417593734373), (2186, 0.0668190550619102), (174, 0.06654779097810146), (2229, 0.06550930349223112), (511, 0.06503816362173509), (1651, 0.0646524098005846), (954, 0.0640326867854636), (3556, 0.06093007456315603), (783, 0.060827352220364596), (203, 0.06064967556538594), (101, 0.06058284032774666), (76, 0.060400593638711766), (3133, 0.060287774483062356), (205, 0.060101386248371476), (182, 0.059669304964216095), (782, 0.059302798976977954), (4033, 0.05922135635911722), (4772, 0.058972046782549414), (1128, 0.0587981

In [102]:
# printing name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1
for movie in sorted_similar_movies:

  index = movie[0]
  
  title_from_index = movies_data[movies_data.index == index]['title'].values[0]

  if i < 20:
    print(i, '.', title_from_index )
    i += 1 

Movies suggested for you : 

1 . Iron Man
2 . Iron Man 3
3 . Iron Man 2
4 . Avengers: Age of Ultron
5 . The Helix... Loaded
6 . The Avengers
7 . Captain America: Civil War
8 . X-Men: Apocalypse
9 . The Nativity Story
10 . X-Men: Days of Future Past
11 . X-Men: The Last Stand
12 . The Hunting Party
13 . A Scanner Darkly
14 . Beyond the Black Rainbow
15 . Arlington Road
16 . Tower Heist
17 . The Shaggy Dog
18 . Zodiac
19 . The Kite Runner


Movie Recommendation System

In [107]:
def movie_recommendation():

  movie_name = input("Enter your favourite movie name : ")

  list_of_all_titles = movies_data['title'].tolist()

  find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

  close_match = find_close_match[0]

  index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

  similarity_score = list(enumerate(similarity[index_of_the_movie]))

  sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse=True)

  i = 1
  for movie in sorted_similar_movies:

    index = movie[0]
    
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]

    if i < 11:
      x = print(i, '.', title_from_index) 
      i += 1 


In [109]:
movie_recommendation()

Enter your favourite movie name : batman
1 . Batman
2 . Batman Begins
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Returns
6 . The Dark Knight
7 . Batman Forever
8 . Batman: The Dark Knight Returns, Part 2
9 . Batman v Superman: Dawn of Justice
10 . Chill Factor
